const TITLE_MARGIN = 32;
const TITLE_HEIGHT = 2;

const PATTERN_TITLE_MARGIN = 24;
const PATTERN_TITLE_HEIGHT = 32;

const GRID_MARGIN = 32;

export {
    TITLE_MARGIN,
    TITLE_HEIGHT,
    PATTERN_TITLE_MARGIN,
    PATTERN_TITLE_HEIGHT,
    GRID_MARGIN,
};
